/* This function was automatically generated by CasADi */
#include <math.h>

#define d double

d sq(d x){ return x*x;}

d sign(d x){ return x<0 ? -1 : x>0 ? 1 : x;}

int s0[] = {8,1,0,1,2,3,4,5,6,7,8,0,0,0,0,0,0,0,0};
int s1[] = {4,8,0,4,8,9,10,0,1,4,5,0,1,4,5,2,3};
int init(int *n_in, int *n_out){
  *n_in = 1;
  *n_out = 1;
  return 0;
}

int getSparsity(int i, int *nrow, int *ncol, int **rowind, int **col){
  int* sp;
  switch(i){
    case 0:
      sp = s0; break;
    case 1:
      sp = s1; break;
    default:
      return 1;
  }

  *nrow = sp[0];
  *ncol = sp[1];
  *rowind = sp + 2;
  *col = sp + 2 + (*nrow + 1);
  return 0;
}

void evaluate(const d* x0,d* r0){ 
  d a0=x0[0];
  d a1=sin(a0);
  a1=(-a1);
  d a2=x0[4];
  a1=(a1/a2);
  if(r0!=0) r0[0]=a1;
  a1=x0[1];
  d a3=sin(a1);
  a3=(-a3);
  d a4=x0[5];
  a3=(a3/a4);
  if(r0!=0) r0[1]=a3;
  a3=cos(a0);
  a3=(a3/a2);
  a3=(-a3);
  a3=(a3/a2);
  if(r0!=0) r0[2]=a3;
  a3=cos(a1);
  a3=(a3/a4);
  a3=(-a3);
  a3=(a3/a4);
  if(r0!=0) r0[3]=a3;
  a3=cos(a0);
  a3=(a3/a2);
  if(r0!=0) r0[4]=a3;
  a3=cos(a1);
  a3=(a3/a4);
  if(r0!=0) r0[5]=a3;
  a0=sin(a0);
  a0=(a0/a2);
  a0=(-a0);
  a0=(a0/a2);
  if(r0!=0) r0[6]=a0;
  a1=sin(a1);
  a1=(a1/a4);
  a1=(-a1);
  a1=(a1/a4);
  if(r0!=0) r0[7]=a1;
  a1=1.0;
  if(r0!=0) r0[8]=a1;
  if(r0!=0) r0[9]=a1;
  a1=x0[2];
  a4=x0[3];
  a0=x0[6];
  a2=x0[7];
}

int evaluateWrap(const d** x, d** r){
  evaluate(x[0],r[0]); 
  return 0;
}

#include <stdio.h>
int main(){
  int i,j;
  d t_x0[8];
  d t_r0[10];
  for(j=0; j<10; ++j){
    for(i=0; i<8; ++i) t_x0[i] = sin(2.2*i+sqrt(4.3/(j+1)));
    evaluate(t_x0,t_r0); 
    printf("%g ",t_r0[0]);
    printf("%g ",t_r0[1]);
    printf("%g ",t_r0[2]);
    printf("%g ",t_r0[3]);
    printf("%g ",t_r0[4]);
    printf("\n");
  }
  return 0;
}

