test: adolc_ex.cpp
	g++ -std=c++0x adolc_ex.cpp -I/usr/include/adolc -ladolc -o test

sparse: sparse_hessian.cpp
	g++ -std=c++0x sparse_hessian.cpp -I/home/gkahn/adolc_base/include -L/home/gkahn/adolc_base/lib64 -ladolc -lColPack -o hess
