% beliefMPC - a fast interior point code generated by FORCES
%
%   OUTPUT = beliefMPC(PARAMS) solves a multistage problem
%   subject to the parameters supplied in the following struct:
%       PARAMS.lb01 - column vector of length 7
%       PARAMS.ub01 - column vector of length 7
%       PARAMS.C01 - matrix of size [10 x 7]
%       PARAMS.e01 - column vector of length 10
%       PARAMS.lb02 - column vector of length 7
%       PARAMS.ub02 - column vector of length 7
%       PARAMS.C02 - matrix of size [5 x 7]
%       PARAMS.e02 - column vector of length 5
%       PARAMS.lb03 - column vector of length 7
%       PARAMS.ub03 - column vector of length 7
%       PARAMS.C03 - matrix of size [5 x 7]
%       PARAMS.e03 - column vector of length 5
%       PARAMS.lb04 - column vector of length 7
%       PARAMS.ub04 - column vector of length 7
%       PARAMS.C04 - matrix of size [5 x 7]
%       PARAMS.e04 - column vector of length 5
%       PARAMS.lb05 - column vector of length 7
%       PARAMS.ub05 - column vector of length 7
%       PARAMS.C05 - matrix of size [5 x 7]
%       PARAMS.e05 - column vector of length 5
%       PARAMS.lb06 - column vector of length 7
%       PARAMS.ub06 - column vector of length 7
%       PARAMS.C06 - matrix of size [5 x 7]
%       PARAMS.e06 - column vector of length 5
%       PARAMS.lb07 - column vector of length 7
%       PARAMS.ub07 - column vector of length 7
%       PARAMS.C07 - matrix of size [5 x 7]
%       PARAMS.e07 - column vector of length 5
%       PARAMS.lb08 - column vector of length 7
%       PARAMS.ub08 - column vector of length 7
%       PARAMS.C08 - matrix of size [5 x 7]
%       PARAMS.e08 - column vector of length 5
%       PARAMS.lb09 - column vector of length 7
%       PARAMS.ub09 - column vector of length 7
%       PARAMS.C09 - matrix of size [5 x 7]
%       PARAMS.e09 - column vector of length 5
%       PARAMS.lb10 - column vector of length 7
%       PARAMS.ub10 - column vector of length 7
%       PARAMS.C10 - matrix of size [5 x 7]
%       PARAMS.e10 - column vector of length 5
%       PARAMS.lb11 - column vector of length 7
%       PARAMS.ub11 - column vector of length 7
%       PARAMS.C11 - matrix of size [5 x 7]
%       PARAMS.e11 - column vector of length 5
%       PARAMS.lb12 - column vector of length 7
%       PARAMS.ub12 - column vector of length 7
%       PARAMS.C12 - matrix of size [5 x 7]
%       PARAMS.e12 - column vector of length 5
%       PARAMS.lb13 - column vector of length 7
%       PARAMS.ub13 - column vector of length 7
%       PARAMS.C13 - matrix of size [5 x 7]
%       PARAMS.e13 - column vector of length 5
%       PARAMS.lb14 - column vector of length 7
%       PARAMS.ub14 - column vector of length 7
%       PARAMS.C14 - matrix of size [5 x 7]
%       PARAMS.e14 - column vector of length 5
%       PARAMS.lb15 - column vector of length 5
%       PARAMS.ub15 - column vector of length 5
%
%   OUTPUT returns the values of the last iteration of the solver where
%       OUTPUT.z1 - column vector of size 7
%       OUTPUT.z2 - column vector of size 7
%       OUTPUT.z3 - column vector of size 7
%       OUTPUT.z4 - column vector of size 7
%       OUTPUT.z5 - column vector of size 7
%       OUTPUT.z6 - column vector of size 7
%       OUTPUT.z7 - column vector of size 7
%       OUTPUT.z8 - column vector of size 7
%       OUTPUT.z9 - column vector of size 7
%       OUTPUT.z10 - column vector of size 7
%       OUTPUT.z11 - column vector of size 7
%       OUTPUT.z12 - column vector of size 7
%       OUTPUT.z13 - column vector of size 7
%       OUTPUT.z14 - column vector of size 7
%       OUTPUT.z15 - column vector of size 5
%
%   [OUTPUT, EXITFLAG] = beliefMPC(PARAMS) returns additionally
%   the integer EXITFLAG indicating the state of the solution with 
%       1 - Optimal solution has been found (subject to desired accuracy)
%       0 - Maximum number of interior point iterations reached
%      -7 - Line search could not progress
%
%   [OUTPUT, EXITFLAG, INFO] = beliefMPC(PARAMS) returns 
%   additional information about the last iterate:
%       INFO.it        - number of iterations that lead to this result
%       INFO.res_eq    - max. equality constraint residual
%       INFO.res_ineq  - max. inequality constraint residual
%       INFO.pobj      - primal objective
%       INFO.dobj      - dual objective
%       INFO.dgap      - duality gap := pobj - dobj
%       INFO.rdgap     - relative duality gap := |dgap / pobj|
%       INFO.mu        - duality measure
%       INFO.sigma     - centering parameter
%       INFO.lsit_aff  - iterations of affine line search
%       INFO.lsit_cc   - iterations of line search (combined direction)
%       INFO.step_aff  - step size (affine direction)
%       INFO.step_cc   - step size (centering direction)
%       INFO.solvetime - Time needed for solve (wall clock time)
%
% See also LICENSE
