% beliefMPC - a fast interior point code generated by FORCES
%
%   OUTPUT = beliefMPC(PARAMS) solves a multistage problem
%   subject to the parameters supplied in the following struct:
%       PARAMS.lb1 - column vector of length 7
%       PARAMS.ub1 - column vector of length 7
%       PARAMS.C1 - matrix of size [10 x 7]
%       PARAMS.e1 - column vector of length 10
%       PARAMS.lb2 - column vector of length 7
%       PARAMS.ub2 - column vector of length 7
%       PARAMS.C2 - matrix of size [5 x 7]
%       PARAMS.e2 - column vector of length 5
%       PARAMS.lb3 - column vector of length 7
%       PARAMS.ub3 - column vector of length 7
%       PARAMS.C3 - matrix of size [5 x 7]
%       PARAMS.e3 - column vector of length 5
%       PARAMS.lb4 - column vector of length 7
%       PARAMS.ub4 - column vector of length 7
%       PARAMS.C4 - matrix of size [5 x 7]
%       PARAMS.e4 - column vector of length 5
%       PARAMS.lb5 - column vector of length 7
%       PARAMS.ub5 - column vector of length 7
%       PARAMS.C5 - matrix of size [5 x 7]
%       PARAMS.e5 - column vector of length 5
%       PARAMS.lb6 - column vector of length 7
%       PARAMS.ub6 - column vector of length 7
%       PARAMS.C6 - matrix of size [5 x 7]
%       PARAMS.e6 - column vector of length 5
%       PARAMS.lb7 - column vector of length 7
%       PARAMS.ub7 - column vector of length 7
%       PARAMS.C7 - matrix of size [5 x 7]
%       PARAMS.e7 - column vector of length 5
%       PARAMS.lb8 - column vector of length 7
%       PARAMS.ub8 - column vector of length 7
%       PARAMS.C8 - matrix of size [5 x 7]
%       PARAMS.e8 - column vector of length 5
%       PARAMS.lb9 - column vector of length 7
%       PARAMS.ub9 - column vector of length 7
%       PARAMS.C9 - matrix of size [5 x 7]
%       PARAMS.e9 - column vector of length 5
%       PARAMS.lb10 - column vector of length 7
%       PARAMS.ub10 - column vector of length 7
%       PARAMS.C10 - matrix of size [5 x 7]
%       PARAMS.e10 - column vector of length 5
%       PARAMS.lb11 - column vector of length 7
%       PARAMS.ub11 - column vector of length 7
%       PARAMS.C11 - matrix of size [5 x 7]
%       PARAMS.e11 - column vector of length 5
%       PARAMS.lb12 - column vector of length 7
%       PARAMS.ub12 - column vector of length 7
%       PARAMS.C12 - matrix of size [5 x 7]
%       PARAMS.e12 - column vector of length 5
%       PARAMS.lb13 - column vector of length 7
%       PARAMS.ub13 - column vector of length 7
%       PARAMS.C13 - matrix of size [5 x 7]
%       PARAMS.e13 - column vector of length 5
%       PARAMS.lb14 - column vector of length 7
%       PARAMS.ub14 - column vector of length 7
%       PARAMS.C14 - matrix of size [5 x 7]
%       PARAMS.e14 - column vector of length 5
%       PARAMS.lb15 - column vector of length 5
%       PARAMS.ub15 - column vector of length 5
%
%   OUTPUT returns the values of the last iteration of the solver where
%       OUTPUT.z1 - column vector of size 7
%       OUTPUT.z2 - column vector of size 7
%       OUTPUT.z3 - column vector of size 7
%       OUTPUT.z4 - column vector of size 7
%       OUTPUT.z5 - column vector of size 7
%       OUTPUT.z6 - column vector of size 7
%       OUTPUT.z7 - column vector of size 7
%       OUTPUT.z8 - column vector of size 7
%       OUTPUT.z9 - column vector of size 7
%       OUTPUT.z10 - column vector of size 7
%       OUTPUT.z11 - column vector of size 7
%       OUTPUT.z12 - column vector of size 7
%       OUTPUT.z13 - column vector of size 7
%       OUTPUT.z14 - column vector of size 7
%       OUTPUT.z15 - column vector of size 5
%
%   [OUTPUT, EXITFLAG] = beliefMPC(PARAMS) returns additionally
%   the integer EXITFLAG indicating the state of the solution with 
%       1 - Optimal solution has been found (subject to desired accuracy)
%       0 - Maximum number of interior point iterations reached
%      -7 - Line search could not progress
%
%   [OUTPUT, EXITFLAG, INFO] = beliefMPC(PARAMS) returns 
%   additional information about the last iterate:
%       INFO.it        - number of iterations that lead to this result
%       INFO.res_eq    - max. equality constraint residual
%       INFO.res_ineq  - max. inequality constraint residual
%       INFO.pobj      - primal objective
%       INFO.dobj      - dual objective
%       INFO.dgap      - duality gap := pobj - dobj
%       INFO.rdgap     - relative duality gap := |dgap / pobj|
%       INFO.mu        - duality measure
%       INFO.sigma     - centering parameter
%       INFO.lsit_aff  - iterations of affine line search
%       INFO.lsit_cc   - iterations of line search (combined direction)
%       INFO.step_aff  - step size (affine direction)
%       INFO.step_cc   - step size (centering direction)
%       INFO.solvetime - Time needed for solve (wall clock time)
%
% See also LICENSE
